import asyncio
import subprocess
import sys
import typer
from sqlalchemy import select, text
from adminfoundry.database import AsyncSessionLocal, engine, get_or_create_tenant_engine
from adminfoundry.models.user import User
from adminfoundry.models.tenant import Tenant
from adminfoundry.auth import hash_password
from adminfoundry.settings import settings

app = typer.Typer(help="coreAdmin management commands.")
db_app = typer.Typer(help="Database management commands.")
extensions_app = typer.Typer(help="Extension management commands.")
tenant_app = typer.Typer(help="Tenant management commands.")

app.add_typer(db_app, name="db")
app.add_typer(extensions_app, name="extensions")
app.add_typer(tenant_app, name="tenant")


# ---------------------------------------------------------------------------
# Top-level commands
# ---------------------------------------------------------------------------

@app.command()
def init(
    directory: str = typer.Argument(".", help="Target directory for the scaffold"),
):
    """Create a minimal coreAdmin app scaffold in the given directory."""
    from pathlib import Path

    base = Path(directory)

    scaffold = '''\
"""Minimal coreAdmin app — generated by coreadmin init."""
from fastapi import FastAPI
from adminfoundry.core.config import CoreAdminConfig
from adminfoundry.admin.router import create_coreadmin
from adminfoundry.admin.model_admin import ModelAdmin
from adminfoundry.admin.registry import admin_site

config = CoreAdminConfig(enable_builtin_ui=True)
app = FastAPI(title="My Admin App")
create_coreadmin(app, config=config)

# Register your first model:
#
# from myapp.models import MyModel
#
# class MyModelAdmin(ModelAdmin):
#     model = MyModel
#     list_display = ["name"]
#     readonly_fields = ["id", "created_at"]
#
# admin_site.register(MyModelAdmin())
'''

    env_example = """\
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/myapp
SECRET_KEY=change-me-in-production
ENABLE_BUILTIN_ADMIN_UI=true
ENABLE_WORKFLOWS=false
"""

    for path, content in [(base / "app.py", scaffold), (base / ".env.example", env_example)]:
        if not path.exists():
            path.write_text(content)
            typer.echo(f"Created {path}")
        else:
            typer.echo(f"Skipped {path} (already exists)")

    typer.echo("\ncoreAdmin scaffold ready. Next steps:")
    typer.echo("  1. pip install adminfoundry[dev]")
    typer.echo("  2. adminfoundry db upgrade")
    typer.echo("  3. adminfoundry create-superadmin")
    typer.echo("  4. uvicorn app:app --reload")


@app.command("create-superadmin")
def create_superadmin(
    email: str = typer.Option(..., prompt=True),
    password: str = typer.Option(..., prompt=True, hide_input=True, confirmation_prompt=True),
    full_name: str = typer.Option(None),
):
    """Create the first superadmin user."""
    asyncio.run(_create_superadmin(email, password, full_name))


async def _create_superadmin(email: str, password: str, full_name: str | None):
    async with AsyncSessionLocal() as session:
        user = User(
            email=email,
            hashed_password=hash_password(password),
            full_name=full_name,
            is_active=True,
            is_superadmin=True,
        )
        session.add(user)
        await session.commit()
        typer.echo(f"Superadmin {email} created.")


@app.command("inspect-registry")
def inspect_registry():
    """Report registered models, fields, actions, protected fields, and contract readiness."""
    import adminfoundry.admin_config  # noqa — trigger registrations
    from adminfoundry.admin.registry import admin_site

    models = admin_site.all()
    if not models:
        typer.echo("No models registered.")
        raise typer.Exit()

    for admin in models:
        typer.echo(f"\n{admin.display_label} ({admin.model_name})")
        typer.echo(f"  list_display:      {admin.list_display}")
        typer.echo(f"  search_fields:     {admin.search_fields}")
        typer.echo(f"  filter_fields:     {admin.filter_fields}")
        typer.echo(f"  readonly_fields:   {admin.readonly_fields}")
        typer.echo(f"  protected_fields:  {sorted(admin.all_protected)}")
        typer.echo(f"  actions:           {[a['name'] for a in admin.actions]}")
        typer.echo(f"  tenant_scoped:     {admin.tenant_scoped}")
        typer.echo(f"  requires_approval: {admin.requires_approval}")
        typer.echo(f"  admin_only:        {admin.admin_only}")

    typer.echo(f"\nTotal: {len(models)} model(s) registered.")


@app.command()
def doctor():
    """Check database connectivity, migration state, extensions, and contract readiness."""
    asyncio.run(_doctor())


async def _doctor():
    from adminfoundry.core.config import CoreAdminConfig
    from adminfoundry.extensions import extension_registry

    config = CoreAdminConfig.from_settings(settings)
    ok = True

    # 1. DB connectivity
    typer.echo("[DB] Checking database connectivity...")
    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
        typer.echo("[DB] OK — connected")
    except Exception as exc:
        typer.echo(f"[DB] FAIL — {exc}", err=True)
        ok = False

    # 2. Admin registry
    typer.echo("\n[Registry] Loading admin registrations...")
    try:
        import adminfoundry.admin_config  # noqa
        from adminfoundry.admin.registry import admin_site
        count = len(admin_site.all())
        typer.echo(f"[Registry] OK — {count} model(s) registered")
    except Exception as exc:
        typer.echo(f"[Registry] FAIL — {exc}", err=True)
        ok = False

    # 3. Config / enabled features
    typer.echo("\n[Config] Enabled features:")
    for key, val in config.to_safe_dict().items():
        typer.echo(f"  {key}: {val}")

    # 4. Extension health
    typer.echo("\n[Extensions] Registered extensions:")
    extensions = extension_registry.all()
    if extensions:
        for ext in extensions:
            h = ext.health_check()
            typer.echo(f"  {ext.name} ({ext.tier}) — {h['status']}")
    else:
        typer.echo("  (none)")

    # 5. Contract readiness
    typer.echo("\n[Contract] Checking admin contract generation...")
    try:
        from adminfoundry.admin.contract import build_model_contract
        from adminfoundry.admin.registry import admin_site
        for adm in admin_site.all():
            build_model_contract(adm, registry=admin_site)
        typer.echo("[Contract] OK")
    except Exception as exc:
        typer.echo(f"[Contract] FAIL — {exc}", err=True)
        ok = False

    typer.echo("")
    if ok:
        typer.echo("doctor: all checks passed.")
    else:
        typer.echo("doctor: some checks failed.", err=True)
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# db sub-commands
# ---------------------------------------------------------------------------

@db_app.command("check")
def db_check():
    """Check database connectivity."""
    asyncio.run(_db_check())


async def _db_check():
    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
        typer.echo("[DB] Connected successfully.")
    except Exception as exc:
        typer.echo(f"[DB] Connection failed: {exc}", err=True)
        raise typer.Exit(code=1)


@db_app.command("upgrade")
def db_upgrade(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Run Alembic migrations (upgrade head) for the given environment."""
    ini = "alembic_shared.ini" if env == "shared" else "alembic_tenant.ini"
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", ini, "upgrade", "head"],
    )
    raise typer.Exit(code=result.returncode)


# ---------------------------------------------------------------------------
# extensions sub-commands
# ---------------------------------------------------------------------------

@extensions_app.command("list")
def extensions_list():
    """List all registered extensions."""
    from adminfoundry.extensions import extension_registry
    exts = extension_registry.all()
    if not exts:
        typer.echo("No extensions registered.")
        return
    typer.echo(f"{'Name':<25} {'Version':<10} {'Tier':<15} {'Optional'}")
    typer.echo("-" * 60)
    for ext in exts:
        typer.echo(f"{ext.name:<25} {ext.version:<10} {ext.tier:<15} {ext.is_optional}")


@extensions_app.command("check")
def extensions_check():
    """Run startup checks for all registered extensions."""
    from adminfoundry.extensions import extension_registry
    exts = extension_registry.all()
    if not exts:
        typer.echo("No extensions registered.")
        return
    all_ok = True
    for ext in exts:
        try:
            ext.startup_check()
            typer.echo(f"  {ext.name}: OK")
        except RuntimeError as exc:
            if not ext.is_optional:
                typer.echo(f"  {ext.name}: FAIL (required) — {exc}", err=True)
                all_ok = False
            else:
                typer.echo(f"  {ext.name}: WARN (optional) — {exc}")
    if not all_ok:
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# tenant sub-commands
# ---------------------------------------------------------------------------

@tenant_app.command("migrate")
def tenant_migrate(slug: str = typer.Argument(..., help="Tenant slug")):
    """Create PostgreSQL schema for a tenant and run tenant migrations."""
    asyncio.run(_migrate_tenant_schema(slug))


@tenant_app.command("upgrade")
def tenant_upgrade(
    all: bool = typer.Option(False, "--all", help="Upgrade all active tenants"),
    slug: str = typer.Option(None, help="Single tenant slug"),
):
    """Upgrade tenant schema(s). Use --all for all active tenants."""
    if all:
        asyncio.run(_migrate_all_tenants())
    elif slug:
        asyncio.run(_migrate_tenant_schema(slug))
    else:
        typer.echo("Provide --all or --slug <slug>.", err=True)
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _migrate_tenant_schema(slug: str):
    if "postgresql" not in settings.DATABASE_URL:
        typer.echo(f"[skip] non-PostgreSQL database — schema creation not applicable for {slug}")
        return

    schema_name = f"tenant_{slug}"
    async with engine.begin() as conn:
        await conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}"'))
    get_or_create_tenant_engine(schema_name)
    typer.echo(f"Schema {schema_name} ready.")


async def _migrate_all_tenants():
    async with AsyncSessionLocal() as session:
        result = await session.execute(select(Tenant).where(Tenant.is_active == True))  # noqa: E712
        tenants = result.scalars().all()

    if not tenants:
        typer.echo("No active tenants found.")
        return

    for tenant in tenants:
        await _migrate_tenant_schema(tenant.slug)


if __name__ == "__main__":
    app()
