import asyncio
import subprocess
import sys
import typer
from sqlalchemy import select, text
from adminfoundry.database import AsyncSessionLocal, engine
from adminfoundry.tenancy.schema_strategy import get_or_create_tenant_engine
from adminfoundry.models.user import User
from adminfoundry.models.tenant import Tenant
from adminfoundry.auth import hash_password
from adminfoundry.settings import settings

app = typer.Typer(help="adminfoundry management commands.")
db_app = typer.Typer(help="Database management commands.")
migrate_app = typer.Typer(help="Migration commands (Alembic wrapper).")
extensions_app = typer.Typer(help="Extension management commands.")
tenant_app = typer.Typer(help="Tenant management commands.")

app.add_typer(db_app, name="db")
app.add_typer(migrate_app, name="migrate")
app.add_typer(extensions_app, name="extensions")
app.add_typer(tenant_app, name="tenant")

# Load plugin commands registered via entry_points group "adminfoundry.commands"
def _load_plugin_commands() -> None:
    try:
        from importlib.metadata import entry_points
        for ep in entry_points(group="adminfoundry.commands"):
            try:
                fn = ep.load()
                app.command(ep.name)(fn)
            except Exception:
                pass
    except Exception:
        pass

_load_plugin_commands()


# ---------------------------------------------------------------------------
# Top-level commands
# ---------------------------------------------------------------------------

@app.command()
def init(
    directory: str = typer.Argument(".", help="Target directory for the scaffold"),
):
    """Create a minimal adminfoundry app scaffold in the given directory."""
    from pathlib import Path

    base = Path(directory)

    scaffold = '''\
"""Minimal adminfoundry app — generated by `adminfoundry init`."""
from adminfoundry import create_admin, CoreAdminConfig
from adminfoundry.admin.model_admin import ModelAdmin
from adminfoundry.admin.registry import admin_site

app = create_admin(config=CoreAdminConfig(), title="My Admin App")

# Register your first model:
#
# from myapp.models import MyModel
#
# class MyModelAdmin(ModelAdmin):
#     model = MyModel
#     list_display = ["name"]
#     readonly_fields = ["id", "created_at"]
#
# admin_site.register(MyModelAdmin())
'''

    env_example = """\
DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/myapp
SECRET_KEY=change-me-in-production
ENABLE_BUILTIN_ADMIN_UI=true
"""

    for path, content in [(base / "app.py", scaffold), (base / ".env.example", env_example)]:
        if not path.exists():
            path.write_text(content)
            typer.echo(f"Created {path}")
        else:
            typer.echo(f"Skipped {path} (already exists)")

    typer.echo("\nadminfoundry scaffold ready. Next steps:")
    typer.echo("  1. pip install adminfoundry[dev]")
    typer.echo("  2. adminfoundry db upgrade")
    typer.echo("  3. adminfoundry create-superadmin")
    typer.echo("  4. uvicorn app:app --reload")


@app.command("create-superadmin")
def create_superadmin(
    email: str = typer.Option(..., prompt=True),
    password: str = typer.Option(..., prompt=True, hide_input=True, confirmation_prompt=True),
    full_name: str = typer.Option(None),
):
    """Create the first superadmin user."""
    asyncio.run(_create_superadmin(email, password, full_name))


async def _create_superadmin(email: str, password: str, full_name: str | None):
    async with AsyncSessionLocal() as session:
        user = User(
            email=email,
            hashed_password=hash_password(password),
            full_name=full_name,
            is_active=True,
            is_superadmin=True,
        )
        session.add(user)
        await session.commit()
        typer.echo(f"Superadmin {email} created.")


@app.command("create-user")
def create_user(
    email: str = typer.Option(..., prompt=True),
    password: str = typer.Option(..., prompt=True, hide_input=True, confirmation_prompt=True),
    full_name: str = typer.Option(None),
    role: str = typer.Option(None, help="Role name to assign (must already exist)"),
    tenant_slug: str = typer.Option(None, help="Tenant slug the role belongs to (for tenant-scoped roles)"),
):
    """Create a regular (non-superadmin) user, optionally assigned to a role."""
    asyncio.run(_create_user(email, password, full_name, role, tenant_slug))


async def _create_user(
    email: str, password: str, full_name: str | None, role_name: str | None, tenant_slug: str | None
):
    async with AsyncSessionLocal() as session:
        user = User(
            email=email,
            hashed_password=hash_password(password),
            full_name=full_name,
            is_active=True,
            is_superadmin=False,
        )
        session.add(user)
        await session.flush()

        if role_name:
            from adminfoundry.models.role import Role, user_roles
            stmt = select(Role).where(Role.name == role_name)
            if tenant_slug:
                tenant = (await session.execute(
                    select(Tenant).where(Tenant.slug == tenant_slug)
                )).scalar_one_or_none()
                if tenant is None:
                    typer.echo(f"Tenant '{tenant_slug}' not found.", err=True)
                    raise typer.Exit(code=1)
                stmt = stmt.where(Role.tenant_id == tenant.id)
            role = (await session.execute(stmt)).scalar_one_or_none()
            if role is None:
                typer.echo(f"Role '{role_name}' not found.", err=True)
                raise typer.Exit(code=1)
            await session.execute(user_roles.insert().values(user_id=user.id, role_id=role.id))
            typer.echo(f"Role '{role_name}' assigned.")

        await session.commit()
        typer.echo(f"User {email} created.")


@app.command("seed-roles")
def seed_roles(
    grant_admin_all: bool = typer.Option(
        False, "--grant-admin-all",
        help="Grant admin role full CRUD on every registered model.",
    ),
    grant_user_read: bool = typer.Option(
        False, "--grant-user-read",
        help="Grant user role list/read access on every registered model.",
    ),
):
    """Create default global roles (admin, user) if they don't already exist.

    Without flags, only the Role records are created — use the permission matrix
    in the admin UI to assign capabilities afterwards.

    With flags, RolePermission rows are written for all currently registered models
    (requires admin_config to be importable so the registry is populated):

    \\b
        adminfoundry seed-roles --grant-admin-all --grant-user-read
    """
    asyncio.run(_seed_roles(grant_admin_all, grant_user_read))


async def _seed_roles(grant_admin_all: bool, grant_user_read: bool):
    from adminfoundry.models.role import Role
    from adminfoundry.models.role_permission import RolePermission

    role_defs = [
        ("admin", "Full admin access"),
        ("user",  "Read-only base role"),
    ]

    async with AsyncSessionLocal() as session:
        # 1 — ensure roles exist, collect their IDs
        role_ids: dict[str, object] = {}
        created_roles: list[str] = []
        for name, desc in role_defs:
            existing = (
                await session.execute(
                    select(Role).where(Role.name == name, Role.tenant_id.is_(None))
                )
            ).scalar_one_or_none()
            if existing is None:
                r = Role(name=name, description=desc)
                session.add(r)
                await session.flush()
                role_ids[name] = r.id
                created_roles.append(name)
            else:
                role_ids[name] = existing.id
        await session.commit()

        if created_roles:
            typer.echo(f"Created roles: {', '.join(created_roles)}")
        else:
            typer.echo("Roles already exist.")

        if not (grant_admin_all or grant_user_read):
            return

        # 2 — import registry (caller is expected to have already imported admin registrations)
        from adminfoundry.admin.registry import admin_site
        model_names = admin_site.model_names()

        if not model_names:
            typer.echo("No models registered — run inside the app context.", err=True)
            return

        grants: list[tuple[str, dict]] = []
        if grant_admin_all:
            grants.append(("admin", dict(can_list=True, can_create=True, can_update=True, can_delete=True)))
        if grant_user_read:
            grants.append(("user", dict(can_list=True, can_create=False, can_update=False, can_delete=False)))

        async with AsyncSessionLocal() as session:
            written = 0
            for role_name, caps in grants:
                rid = role_ids[role_name]
                for mn in model_names:
                    existing = (
                        await session.execute(
                            select(RolePermission).where(
                                RolePermission.role_id == rid,
                                RolePermission.model_name == mn,
                            )
                        )
                    ).scalar_one_or_none()
                    if existing is None:
                        session.add(RolePermission(role_id=rid, model_name=mn, **caps))
                        written += 1
                    else:
                        for k, v in caps.items():
                            setattr(existing, k, v)
                        written += 1
            await session.commit()
        typer.echo(f"Wrote {written} permission rows for {len(model_names)} models.")


@app.command("inspect-registry")
def inspect_registry():
    """Report registered models, fields, actions, protected fields, and contract readiness."""
    from adminfoundry.admin.registry import admin_site

    models = admin_site.all()
    if not models:
        typer.echo("No models registered.")
        raise typer.Exit()

    for admin in models:
        typer.echo(f"\n{admin.display_label} ({admin.model_name})")
        typer.echo(f"  list_display:      {admin.list_display}")
        typer.echo(f"  search_fields:     {admin.search_fields}")
        typer.echo(f"  filter_fields:     {admin.filter_fields}")
        typer.echo(f"  readonly_fields:   {admin.readonly_fields}")
        typer.echo(f"  protected_fields:  {sorted(admin.all_protected)}")
        typer.echo(f"  actions:           {[a['name'] for a in admin.actions]}")
        typer.echo(f"  tenant_scoped:     {admin.tenant_scoped}")
        typer.echo(f"  requires_approval: {admin.requires_approval}")
        typer.echo(f"  admin_only:        {admin.admin_only}")

    typer.echo(f"\nTotal: {len(models)} model(s) registered.")


@app.command()
def doctor():
    """Check database connectivity, migration state, extensions, and contract readiness."""
    asyncio.run(_doctor())


async def _doctor():
    from adminfoundry.core.config import CoreAdminConfig
    from adminfoundry.extensions import extension_registry

    config = CoreAdminConfig.from_settings(settings)
    ok = True

    # 1. DB connectivity
    typer.echo("[DB] Checking database connectivity...")
    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
        typer.echo("[DB] OK — connected")
    except Exception as exc:
        typer.echo(f"[DB] FAIL — {exc}", err=True)
        ok = False

    # 2. Admin registry
    typer.echo("\n[Registry] Loading admin registrations...")
    try:
        from adminfoundry.admin.registry import admin_site
        count = len(admin_site.all())
        typer.echo(f"[Registry] OK — {count} model(s) registered")
    except Exception as exc:
        typer.echo(f"[Registry] FAIL — {exc}", err=True)
        ok = False

    # 3. Config / enabled features
    typer.echo("\n[Config] Enabled features:")
    for key, val in config.to_safe_dict().items():
        typer.echo(f"  {key}: {val}")

    # 4. Extension health
    typer.echo("\n[Extensions] Registered extensions:")
    extensions = extension_registry.all()
    if extensions:
        for ext in extensions:
            h = ext.health_check()
            typer.echo(f"  {ext.name} — {h['status']}")
    else:
        typer.echo("  (none)")

    # 5. Contract readiness
    typer.echo("\n[Contract] Checking admin contract generation...")
    try:
        from adminfoundry.admin.contract import build_model_contract
        from adminfoundry.admin.registry import admin_site
        for adm in admin_site.all():
            build_model_contract(adm, registry=admin_site)
        typer.echo("[Contract] OK")
    except Exception as exc:
        typer.echo(f"[Contract] FAIL — {exc}", err=True)
        ok = False

    typer.echo("")
    if ok:
        typer.echo("doctor: all checks passed.")
    else:
        typer.echo("doctor: some checks failed.", err=True)
        raise typer.Exit(code=1)


@app.command("cleanup")
def cleanup(
    once: bool = typer.Option(
        False, "--once", help="Run the cleanup pass once and exit."
    ),
):
    """Purge expired revoked tokens, password-reset tokens, and old audit logs."""
    if not once:
        typer.echo("Pass --once to run the cleanup pass now.", err=True)
        raise typer.Exit(code=1)
    from adminfoundry.cleanup import _run_cleanup
    asyncio.run(_run_cleanup())
    typer.echo("Cleanup complete.")


# ---------------------------------------------------------------------------
# migrate sub-commands (Alembic wrapper)
# ---------------------------------------------------------------------------

@migrate_app.command("generate")
def migrate_generate(
    message: str = typer.Option("auto", "-m", "--message", help="Migration message"),
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Auto-generate a new Alembic migration from model changes."""
    ini = "alembic_shared.ini" if env == "shared" else "alembic_tenant.ini"
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", ini, "revision", "--autogenerate", "-m", message],
    )
    raise typer.Exit(code=result.returncode)


@migrate_app.command("apply")
def migrate_apply(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
    revision: str = typer.Option("head", help="Target revision (default: head)"),
):
    """Apply pending migrations (upgrade to head by default)."""
    ini = "alembic_shared.ini" if env == "shared" else "alembic_tenant.ini"
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", ini, "upgrade", revision],
    )
    raise typer.Exit(code=result.returncode)


@migrate_app.command("status")
def migrate_status(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Show current migration revision and pending migrations."""
    ini = "alembic_shared.ini" if env == "shared" else "alembic_tenant.ini"
    subprocess.run([sys.executable, "-m", "alembic", "-c", ini, "current"])
    subprocess.run([sys.executable, "-m", "alembic", "-c", ini, "heads"])


# ---------------------------------------------------------------------------
# db sub-commands
# ---------------------------------------------------------------------------

@db_app.command("check")
def db_check():
    """Check database connectivity."""
    asyncio.run(_db_check())


async def _db_check():
    try:
        async with engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
        typer.echo("[DB] Connected successfully.")
    except Exception as exc:
        typer.echo(f"[DB] Connection failed: {exc}", err=True)
        raise typer.Exit(code=1)


@db_app.command("upgrade")
def db_upgrade(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Run Alembic migrations (upgrade head) for the given environment."""
    ini = "alembic_shared.ini" if env == "shared" else "alembic_tenant.ini"
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", ini, "upgrade", "head"],
    )
    raise typer.Exit(code=result.returncode)


# ---------------------------------------------------------------------------
# extensions sub-commands
# ---------------------------------------------------------------------------

@extensions_app.command("list")
def extensions_list():
    """List all registered extensions."""
    from adminfoundry.extensions import extension_registry
    exts = extension_registry.all()
    if not exts:
        typer.echo("No extensions registered.")
        return
    typer.echo(f"{'Name':<25} {'Version':<10} {'Optional'}")
    typer.echo("-" * 45)
    for ext in exts:
        typer.echo(f"{ext.name:<25} {ext.version:<10} {ext.is_optional}")


@extensions_app.command("check")
def extensions_check():
    """Run startup checks for all registered extensions."""
    from adminfoundry.extensions import extension_registry
    exts = extension_registry.all()
    if not exts:
        typer.echo("No extensions registered.")
        return
    all_ok = True
    for ext in exts:
        try:
            ext.startup_check()
            typer.echo(f"  {ext.name}: OK")
        except RuntimeError as exc:
            if not ext.is_optional:
                typer.echo(f"  {ext.name}: FAIL (required) — {exc}", err=True)
                all_ok = False
            else:
                typer.echo(f"  {ext.name}: WARN (optional) — {exc}")
    if not all_ok:
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# tenant sub-commands
# ---------------------------------------------------------------------------

@tenant_app.command("migrate")
def tenant_migrate(slug: str = typer.Argument(..., help="Tenant slug")):
    """Create PostgreSQL schema for a tenant and run tenant migrations."""
    asyncio.run(_migrate_tenant_schema(slug))


@tenant_app.command("upgrade")
def tenant_upgrade(
    all: bool = typer.Option(False, "--all", help="Upgrade all active tenants"),
    slug: str = typer.Option(None, help="Single tenant slug"),
):
    """Upgrade tenant schema(s). Use --all for all active tenants."""
    if all:
        asyncio.run(_migrate_all_tenants())
    elif slug:
        asyncio.run(_migrate_tenant_schema(slug))
    else:
        typer.echo("Provide --all or --slug <slug>.", err=True)
        raise typer.Exit(code=1)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

async def _migrate_tenant_schema(slug: str):
    if "postgresql" not in settings.DATABASE_URL:
        typer.echo(f"[skip] non-PostgreSQL database — schema creation not applicable for {slug}")
        return

    schema_name = f"tenant_{slug}"
    async with engine.begin() as conn:
        await conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}"'))
    get_or_create_tenant_engine(schema_name)
    typer.echo(f"Schema {schema_name} ready.")


async def _migrate_all_tenants():
    async with AsyncSessionLocal() as session:
        result = await session.execute(select(Tenant).where(Tenant.is_active == True))  # noqa: E712
        tenants = result.scalars().all()

    if not tenants:
        typer.echo("No active tenants found.")
        return

    for tenant in tenants:
        await _migrate_tenant_schema(tenant.slug)


if __name__ == "__main__":
    app()
