"""Transactional email outbox (self-contained extension subsystem).

Sending email inline in a request couples the request's success to the mail
server: a slow/failing SMTP call slows or breaks the invite/reset response, and
a one-shot send has no retry. The outbox decouples them:

1. :class:`OutboxEmailNotifier` wraps a real notifier and, instead of sending,
   **persists** the rendered email as an ``email_outbox`` row — ideally in the
   *same* DB transaction as the invite/user that triggered it (so you never get
   "user created but email lost", nor the reverse). It joins that transaction
   via ``request.state.db_session`` (set by the framework's
   ``get_async_session``); outside a request it falls back to a supplied
   ``session_factory``.
2. A worker (:func:`process_outbox`) — run from your own cron/loop — picks up
   pending rows and sends them through the real notifier, with bounded retries
   and backoff.

Migration story (matches the ``auth_oauth`` extension): the framework ships
**no** Alembic migration for ``email_outbox``. Import this module so the model
registers on the global metadata, then ``alembic revision --autogenerate``
against your env.py picks it up — asterion's bundled migration tree stays free
of extension tables.
"""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractAsyncContextManager
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any

from sqlalchemy import DateTime, Integer, String, Text, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import Mapped, mapped_column

from asterion.extensions.email.notifier import BaseEmailNotifier, EmailContent
from asterion.models.base import GlobalModel

if TYPE_CHECKING:  # pragma: no cover
    from fastapi import Request

SessionFactory = Callable[[], AbstractAsyncContextManager[AsyncSession]]

STATUS_PENDING = "pending"
STATUS_SENT = "sent"
STATUS_FAILED = "failed"


class EmailOutbox(GlobalModel):
    """One queued email. Lives in the public schema alongside other global
    tables; the host app creates it via its own autogenerated migration."""

    __tablename__ = "email_outbox"

    to_addr: Mapped[str] = mapped_column(String(320), nullable=False)
    subject: Mapped[str] = mapped_column(String(500), nullable=False)
    body_text: Mapped[str] = mapped_column(Text, nullable=False)
    body_html: Mapped[str | None] = mapped_column(Text, nullable=True)

    #: ``pending`` → ``sent`` | ``failed`` (after max attempts).
    status: Mapped[str] = mapped_column(
        String(16), default=STATUS_PENDING, nullable=False, index=True
    )
    attempts: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    #: Earliest time the row is eligible to send (used for retry backoff).
    scheduled_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


def enqueue_email(
    session: AsyncSession,
    *,
    to: str,
    content: EmailContent,
    scheduled_at: datetime | None = None,
) -> EmailOutbox:
    """Add one :class:`EmailOutbox` row to ``session`` (no commit — the caller's
    transaction owns it)."""
    row = EmailOutbox(
        to_addr=to,
        subject=content.subject,
        body_text=content.text,
        body_html=content.html,
        status=STATUS_PENDING,
        attempts=0,
        scheduled_at=scheduled_at or datetime.now(UTC),
    )
    session.add(row)
    return row


class OutboxEmailNotifier:
    """Notifier that **enqueues** instead of sending.

    Satisfies both framework notifier Protocols (``send_reset`` /
    ``send_invite``) plus the generic ``send``. Rendering is delegated to
    ``inner`` (any :class:`BaseEmailNotifier`), so templates/branding work
    exactly as for direct delivery; only the transport differs.
    """

    def __init__(
        self,
        inner: BaseEmailNotifier,
        *,
        session_factory: SessionFactory | None = None,
    ) -> None:
        self.inner = inner
        self._session_factory = session_factory

    async def send_reset(self, *, email: str, token: str, request: Request | None = None) -> None:
        content = self.inner.render_reset(email=email, token=token, request=request)
        await self._enqueue(email, content, request)

    async def send_invite(
        self,
        *,
        email: str,
        token: str,
        tenant_slug: str | None = None,
        request: Request | None = None,
    ) -> None:
        content = self.inner.render_invite(
            email=email, token=token, tenant_slug=tenant_slug, request=request
        )
        await self._enqueue(email, content, request)

    async def send(
        self,
        event: str,
        to: str,
        *,
        context: dict[str, Any] | None = None,
        request: Request | None = None,
    ) -> None:
        content = self.inner.render_event(
            event=event, to=to, context=context or {}, request=request
        )
        await self._enqueue(to, content, request)

    async def _enqueue(
        self,
        to: str,
        content: EmailContent,
        request: Request | None,
    ) -> None:
        # Prefer the request-scoped session so the row commits atomically with
        # whatever triggered the email (transactional outbox).
        session = getattr(getattr(request, "state", None), "db_session", None)
        if session is not None:
            enqueue_email(session, to=to, content=content)
            return
        # Out-of-request (e.g. a background job): own short transaction.
        if self._session_factory is not None:
            async with self._session_factory() as own:
                async with own.begin():
                    enqueue_email(own, to=to, content=content)
            return
        raise RuntimeError(
            "OutboxEmailNotifier has no session: it needs either a request with "
            "request.state.db_session (set by get_async_session) or a "
            "session_factory= passed at construction."
        )


def _backoff(attempts: int) -> timedelta:
    """Exponential-ish backoff capped at ~1h: 1, 4, 9, … minutes."""
    return timedelta(minutes=min(attempts * attempts, 60))


async def process_outbox(
    session: AsyncSession,
    notifier: BaseEmailNotifier,
    *,
    batch: int = 20,
    max_attempts: int = 5,
    now: datetime | None = None,
) -> dict[str, int]:
    """Send up to ``batch`` due pending emails through ``notifier``.

    Run from your own cron/loop. Returns ``{"sent": n, "failed": n,
    "retried": n}``. A send failure increments ``attempts`` and reschedules
    with backoff; once ``attempts`` reaches ``max_attempts`` the row is marked
    ``failed``. Commits via the caller's session transaction.
    """
    now = now or datetime.now(UTC)
    rows = (
        (
            await session.execute(
                select(EmailOutbox)
                .where(EmailOutbox.status == STATUS_PENDING, EmailOutbox.scheduled_at <= now)
                .order_by(EmailOutbox.created_at)
                .limit(batch)
            )
        )
        .scalars()
        .all()
    )

    sent = failed = retried = 0
    for row in rows:
        content = EmailContent(subject=row.subject, text=row.body_text, html=row.body_html)
        try:
            await notifier.deliver(to=row.to_addr, content=content)
        except Exception as exc:
            row.attempts += 1
            row.last_error = str(exc)
            if row.attempts >= max_attempts:
                row.status = STATUS_FAILED
                failed += 1
            else:
                row.scheduled_at = now + _backoff(row.attempts)
                retried += 1
        else:
            row.status = STATUS_SENT
            row.sent_at = now
            sent += 1

    await session.flush()
    return {"sent": sent, "failed": failed, "retried": retried}
