"""asterion management CLI.

Subcommands are organized into:
  * top-level: create-superadmin, doctor, init, inspect-registry
  * db:        check, upgrade, upgrade-public, upgrade-tenant, upgrade-tenants, current, heads
  * migrate:   generate, apply, status
  * tenant:    create, list, bootstrap, upgrade
  * permissions: sync, list, check
  * service-account: create
"""

from __future__ import annotations

import asyncio
import importlib
import subprocess
import sys
from datetime import UTC
from pathlib import Path

import typer
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from asterion.auth.password import hash_password
from asterion.core.config import CoreAdminConfig
from asterion.db.alembic_support import (
    set_x_schema,
    shared_alembic_config,
    tenant_alembic_config,
)
from asterion.db.session import DatabaseManager
from asterion.models.tenant import Tenant
from asterion.models.user import User
from asterion.security.validation import (
    ValidationError,
    validate_permission_key,
    validate_tenant_slug,
)
from asterion.tenancy.bootstrap import (
    assign_owner_membership,
    bootstrap_tenant,
    create_tenant_record,
)

app = typer.Typer(help="asterion management commands.")
db_app = typer.Typer(help="Database management commands.")
migrate_app = typer.Typer(help="Migration commands (Alembic wrapper).")
tenant_app = typer.Typer(help="Tenant management commands.")
permissions_app = typer.Typer(help="Permission catalog management.")
user_app = typer.Typer(help="User management commands.")
audit_app = typer.Typer(help="Audit log management.")
service_account_app = typer.Typer(help="Service / machine account management.")

app.add_typer(db_app, name="db")
app.add_typer(migrate_app, name="migrate")
app.add_typer(tenant_app, name="tenant")
app.add_typer(permissions_app, name="permissions")
app.add_typer(user_app, name="user")
app.add_typer(audit_app, name="audit")
app.add_typer(service_account_app, name="service-account")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_config() -> CoreAdminConfig:
    try:
        return CoreAdminConfig.from_env()
    except ValueError as exc:
        typer.echo(f"Config error: {exc}", err=True)
        raise typer.Exit(code=1) from exc


def _make_db(config: CoreAdminConfig) -> DatabaseManager:
    return DatabaseManager(config.database_url, echo=config.debug)


async def _find_user_by_email(session: AsyncSession, email: str) -> User | None:
    result = await session.execute(select(User).where(User.email == email))
    return result.scalar_one_or_none()


# ---------------------------------------------------------------------------
# Top-level commands
# ---------------------------------------------------------------------------


@app.command()
def init(
    directory: str = typer.Argument(".", help="Target directory for the scaffold"),
):
    """Create a minimal asterion app scaffold in the given directory."""
    base = Path(directory)

    scaffold = '''\
"""Minimal asterion app — generated by `asterion init`."""
from asterion import CoreAdminConfig, create_admin

app = create_admin(config=CoreAdminConfig.from_env())
'''

    env_example = """\
ASTERION_DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/myapp
# Required. Generate via: openssl rand -hex 32
ASTERION_SECRET_KEY=
"""

    for path, content in [(base / "app.py", scaffold), (base / ".env.example", env_example)]:
        if not path.exists():
            path.write_text(content)
            typer.echo(f"Created {path}")
        else:
            typer.echo(f"Skipped {path} (already exists)")

    typer.echo("\nasterion scaffold ready. Next steps:")
    typer.echo("  1. Set ASTERION_DATABASE_URL and ASTERION_SECRET_KEY")
    typer.echo("  2. asterion db upgrade")
    typer.echo("  3. asterion create-superadmin")
    typer.echo("  4. uvicorn app:app --reload")


@app.command("create-superadmin")
def create_superadmin(
    email: str = typer.Option(..., prompt=True),
    password: str = typer.Option(..., prompt=True, hide_input=True, confirmation_prompt=True),
    full_name: str | None = typer.Option(None),
):
    """Create the first superadmin user (idempotent by email)."""
    asyncio.run(_create_superadmin(email, password, full_name))


async def _create_superadmin(email: str, password: str, full_name: str | None) -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            async with session.begin():
                existing = await _find_user_by_email(session, email)
                if existing is not None:
                    existing.is_superadmin = True
                    existing.is_active = True
                    typer.echo(f"Promoted existing user {email} to superadmin.")
                    return
                session.add(
                    User(
                        email=email,
                        hashed_password=hash_password(password),
                        full_name=full_name,
                        is_active=True,
                        is_superadmin=True,
                    )
                )
        typer.echo(f"Superadmin {email} created.")
    finally:
        await db.dispose()


@app.command("inspect-registry")
def inspect_registry():
    """Report registered models — requires the app to be importable."""
    typer.echo(
        "inspect-registry requires the app to be imported with its registry populated.\n"
        "Run from within the app context using a startup hook or app.py."
    )


@app.command()
def doctor(
    app_spec: str = typer.Option(
        "",
        "--app",
        envvar="ASTERION_APP",
        help=(
            "Optional 'module:attribute' pointing at the FastAPI app. "
            "Enables the [REG] registry check."
        ),
    ),
):
    """Verify config, DB connectivity, permission catalog, and (with --app) registry health."""
    asyncio.run(_doctor(app_spec))


async def _doctor(app_spec: str) -> None:
    failures: list[str] = []

    typer.echo("[CFG] Loading CoreAdminConfig.from_env() ...")
    try:
        config = CoreAdminConfig.from_env()
    except ValueError as exc:
        typer.echo(f"[CFG] FAIL — {exc}", err=True)
        raise typer.Exit(code=1) from exc
    typer.echo(f"[CFG] OK (environment={config.environment})")

    typer.echo("[VER] asterion version ...")
    try:
        import asterion as _af

        typer.echo(f"[VER] OK ({_af.__version__})")
    except Exception as exc:
        typer.echo(f"[VER] WARN — {exc}")

    typer.echo("[DB]  Checking database connectivity ...")
    db = _make_db(config)
    try:
        async with db.engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
        typer.echo("[DB]  OK")
    except Exception as exc:
        typer.echo(f"[DB]  FAIL — {exc}", err=True)
        failures.append("db")

    typer.echo("[CAT] PermissionCatalog populated ...")
    try:
        from sqlalchemy import func as _func

        from asterion.models.permission_catalog import PermissionCatalog

        async with db.session() as session:
            count = (await session.execute(_func.count(PermissionCatalog.id).select())).scalar_one()
        if count == 0:
            typer.echo(
                "[CAT] WARN — PermissionCatalog is empty. "
                "Run `asterion permissions sync --app <module:attr>`."
            )
        else:
            typer.echo(f"[CAT] OK ({count} permission key(s))")
    except Exception as exc:
        typer.echo(f"[CAT] WARN — {exc}")

    typer.echo("[MT]  Multi-tenant config ...")
    if config.enable_multi_tenant:
        if not config.tenant_header_name.strip():
            typer.echo("[MT]  FAIL — tenant_header_name empty", err=True)
            failures.append("multi-tenant header")
        elif config.database_url.startswith(("sqlite://", "sqlite+aiosqlite://")):
            typer.echo(
                "[MT]  WARN — multi-tenant on SQLite is dev-only; isolation requires PostgreSQL."
            )
        else:
            typer.echo(
                f"[MT]  OK (resolution={config.tenant_resolution}, header={config.tenant_header_name})"
            )
    else:
        typer.echo("[MT]  OK (disabled)")

    typer.echo("[CORS] CORS config ...")
    if not config.cors_origins:
        typer.echo("[CORS] OK (middleware not installed; no origins configured)")
    else:
        if config.cors_allow_credentials and "*" in config.cors_origins:
            typer.echo("[CORS] FAIL — cors_origins=['*'] + credentials=True", err=True)
            failures.append("cors")
        else:
            typer.echo(f"[CORS] OK ({len(config.cors_origins)} origin(s))")

    typer.echo("[REG] Registered resources ...")
    if not app_spec:
        typer.echo("[REG] SKIP (pass --app or set ASTERION_APP to enable)")
    else:
        try:
            registry = _load_registry_from_app_spec(app_spec)
            names = registry.model_names()
            if not names:
                typer.echo("[REG] WARN — registry is empty.")
            else:
                typer.echo(f"[REG] OK ({len(names)} resource(s): {', '.join(sorted(names))})")
        except typer.Exit:
            failures.append("registry")
        except Exception as exc:
            typer.echo(f"[REG] WARN — {exc}")

    await db.dispose()

    if failures:
        typer.echo(f"\ndoctor: FAILED — {', '.join(failures)}", err=True)
        raise typer.Exit(code=1)
    typer.echo("\ndoctor: all checks passed.")


# ---------------------------------------------------------------------------
# migrate sub-commands (Alembic wrapper)
# ---------------------------------------------------------------------------


def _alembic_ini(env: str) -> str:
    if env not in {"shared", "tenant"}:
        typer.echo(f"Unknown migration environment: {env}", err=True)
        raise typer.Exit(code=2)
    return "alembic_shared.ini" if env == "shared" else "alembic_tenant.ini"


@migrate_app.command("generate")
def migrate_generate(
    message: str = typer.Option("auto", "-m", "--message", help="Migration message"),
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Auto-generate a new Alembic migration from model changes."""
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "alembic",
            "-c",
            _alembic_ini(env),
            "revision",
            "--autogenerate",
            "-m",
            message,
        ],
    )
    raise typer.Exit(code=result.returncode)


@migrate_app.command("apply")
def migrate_apply(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
    revision: str = typer.Option("head", help="Target revision (default: head)"),
):
    """Apply pending migrations."""
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", _alembic_ini(env), "upgrade", revision],
    )
    raise typer.Exit(code=result.returncode)


@migrate_app.command("status")
def migrate_status(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Show current migration revision."""
    ini = _alembic_ini(env)
    subprocess.run([sys.executable, "-m", "alembic", "-c", ini, "current"])
    subprocess.run([sys.executable, "-m", "alembic", "-c", ini, "heads"])


# ---------------------------------------------------------------------------
# db sub-commands
# ---------------------------------------------------------------------------


@db_app.command("check")
def db_check():
    """Check database connectivity."""
    asyncio.run(_db_check())


async def _db_check() -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.engine.begin() as conn:
            await conn.execute(text("SELECT 1"))
        typer.echo("[DB] Connected successfully.")
    except Exception as exc:
        typer.echo(f"[DB] Connection failed: {exc}", err=True)
        raise typer.Exit(code=1) from exc
    finally:
        await db.dispose()


@db_app.command("upgrade")
def db_upgrade(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Run Alembic migrations (upgrade head). Kept for backward compatibility;
    prefer ``db upgrade-public`` / ``db upgrade-tenant <slug>``."""
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", _alembic_ini(env), "upgrade", "head"],
    )
    raise typer.Exit(code=result.returncode)


@db_app.command("upgrade-public")
def db_upgrade_public():
    """Apply all pending public/shared-schema migrations bundled with asterion.

    Runs asterion's own (bundled) shared migrations package-relatively, so it
    works from any cwd and from a pip-installed wheel. The DB URL comes from
    ``ASTERION_DATABASE_URL`` / ``DATABASE_URL``.
    """
    from alembic import command

    try:
        command.upgrade(shared_alembic_config(), "head")
    except Exception as exc:
        typer.echo(f"[db] upgrade-public failed: {exc}", err=True)
        raise typer.Exit(code=1) from exc


@db_app.command("upgrade-tenant")
def db_upgrade_tenant(
    slug: str = typer.Argument(..., help="Tenant slug"),
    config: str | None = typer.Option(
        None,
        "-c",
        "--config",
        help="Path to a tenant alembic .ini (overrides auto-resolution).",
    ),
):
    """Apply pending tenant-schema migrations for one tenant.

    Resolves the tenant's schema_name via the slug and passes it to alembic as
    ``-x schema=<schema_name>``. The tenant migrations tree is owned by the
    downstream app — see :func:`asterion.db.alembic_support.tenant_alembic_config` for the resolution
    order (explicit ``-c`` > local ``alembic_tenant.ini`` > asterion's bundled
    tenant migrations).
    """
    try:
        validated = validate_tenant_slug(slug)
    except ValidationError as exc:
        typer.echo(f"Invalid slug: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    from alembic import command

    from asterion.tenancy.schema_names import make_tenant_schema_name

    schema_name = make_tenant_schema_name(validated)
    cfg = tenant_alembic_config(config)
    set_x_schema(cfg, schema_name)
    try:
        command.upgrade(cfg, "head")
    except Exception as exc:
        typer.echo(f"[db] upgrade-tenant failed: {exc}", err=True)
        raise typer.Exit(code=1) from exc


@db_app.command("upgrade-tenants")
def db_upgrade_tenants(
    config: str | None = typer.Option(
        None,
        "-c",
        "--config",
        help="Path to a tenant alembic .ini (overrides auto-resolution).",
    ),
):
    """Apply pending tenant-schema migrations for every active tenant."""
    tenants = asyncio.run(_fetch_active_tenants())
    if not tenants:
        typer.echo("No active tenants found.")
        return

    from alembic import command

    failures: list[str] = []
    for slug, schema_name in tenants:
        typer.echo(f"[upgrade] {slug} ({schema_name})")
        cfg = tenant_alembic_config(config)
        set_x_schema(cfg, schema_name)
        try:
            command.upgrade(cfg, "head")
        except Exception as exc:
            typer.echo(f"  FAILED: {exc}", err=True)
            failures.append(slug)

    if failures:
        typer.echo(f"FAILED: {', '.join(failures)}", err=True)
        raise typer.Exit(code=1)
    typer.echo(f"Upgraded {len(tenants)} tenant(s).")


async def _fetch_active_tenants() -> list[tuple[str, str]]:
    """Return ``(slug, schema_name)`` for every active tenant, detached from
    the session so the caller can run alembic synchronously afterwards (the
    alembic env runs its own event loop, so it must not be nested inside this
    one)."""
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            result = await session.execute(
                select(Tenant).where(Tenant.is_active == True)  # noqa: E712
            )
            return [(t.slug, t.schema_name) for t in result.scalars().all()]
    finally:
        await db.dispose()


@db_app.command("current")
def db_current(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
    slug: str | None = typer.Option(
        None,
        "--slug",
        help="Tenant slug (only meaningful with env=tenant)",
    ),
):
    """Show the current applied migration revision."""
    args = [sys.executable, "-m", "alembic", "-c", _alembic_ini(env), "current"]
    if env == "tenant" and slug:
        from asterion.tenancy.schema_names import make_tenant_schema_name

        validated = validate_tenant_slug(slug)
        schema_name = make_tenant_schema_name(validated)
        args = [*args[:4], "-x", f"schema={schema_name}", *args[4:]]
    result = subprocess.run(args)
    raise typer.Exit(code=result.returncode)


@db_app.command("heads")
def db_heads(
    env: str = typer.Option("shared", help="Migration environment: shared or tenant"),
):
    """Show the latest available migration head(s) for the given env."""
    result = subprocess.run(
        [sys.executable, "-m", "alembic", "-c", _alembic_ini(env), "heads"],
    )
    raise typer.Exit(code=result.returncode)


# ---------------------------------------------------------------------------
# tenant sub-commands
# ---------------------------------------------------------------------------


@tenant_app.command("create")
def tenant_create(
    name: str = typer.Option(..., "--name", help="Display name of the tenant"),
    slug: str = typer.Option(..., "--slug", help="URL-safe tenant slug"),
    owner_email: str | None = typer.Option(
        None,
        "--owner-email",
        help="Email of the owner user. If --create-owner is set, the user is "
        "created when missing; otherwise the user must already exist.",
    ),
    create_owner: bool = typer.Option(
        False,
        "--create-owner",
        help="Create the owner user if not found. Requires --owner-password.",
    ),
    owner_password: str | None = typer.Option(
        None,
        "--owner-password",
        help="Password used when creating a new owner user.",
    ),
    owner_full_name: str | None = typer.Option(
        None, "--owner-full-name", help="Optional full name for a new owner user."
    ),
    skip_schema: bool = typer.Option(
        False,
        "--skip-schema",
        help="Skip PostgreSQL schema provisioning (useful for tests).",
    ),
):
    """Create a tenant. Idempotent: re-running on an existing slug updates."""
    asyncio.run(
        _tenant_create(
            name=name,
            slug=slug,
            owner_email=owner_email,
            create_owner=create_owner,
            owner_password=owner_password,
            owner_full_name=owner_full_name,
            skip_schema=skip_schema,
        )
    )


async def _tenant_create(
    *,
    name: str,
    slug: str,
    owner_email: str | None,
    create_owner: bool,
    owner_password: str | None,
    owner_full_name: str | None,
    skip_schema: bool,
) -> None:
    try:
        slug = validate_tenant_slug(slug)
    except ValidationError as exc:
        typer.echo(f"Invalid slug: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    config = _load_config()
    db = _make_db(config)

    owner_membership_id = None
    try:
        async with db.session() as session:
            async with session.begin():
                tenant = await create_tenant_record(session, name=name, slug=slug)

                if owner_email:
                    owner = await _find_user_by_email(session, owner_email)
                    if owner is None:
                        if not create_owner:
                            typer.echo(
                                f"Owner user {owner_email!r} not found. "
                                "Re-run with --create-owner --owner-password to create it.",
                                err=True,
                            )
                            raise typer.Exit(code=2)
                        if not owner_password:
                            typer.echo(
                                "--owner-password is required when --create-owner is set.",
                                err=True,
                            )
                            raise typer.Exit(code=2)
                        owner = User(
                            email=owner_email,
                            hashed_password=hash_password(owner_password),
                            full_name=owner_full_name,
                            is_active=True,
                            is_superadmin=False,
                        )
                        session.add(owner)
                        await session.flush()

                    membership = await assign_owner_membership(session, tenant=tenant, user=owner)
                    owner_membership_id = membership.id

        if not skip_schema:
            async with db.session() as session:
                await bootstrap_tenant(
                    slug,
                    session,
                    owner_membership_id=owner_membership_id,
                    database_url=config.database_url,
                )

        typer.echo(f"Tenant {slug!r} ready.")
    finally:
        await db.dispose()


@tenant_app.command("list")
def tenant_list():
    """List all tenants in the public schema."""
    asyncio.run(_tenant_list())


async def _tenant_list() -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            result = await session.execute(select(Tenant).order_by(Tenant.slug))
            tenants = result.scalars().all()
    finally:
        await db.dispose()

    if not tenants:
        typer.echo("No tenants registered.")
        return

    typer.echo(f"{'SLUG':<24} {'NAME':<32} {'SCHEMA':<24} ACTIVE")
    for tenant in tenants:
        typer.echo(
            f"{tenant.slug:<24} {tenant.name:<32} {tenant.schema_name:<24} {tenant.is_active}"
        )


@tenant_app.command("bootstrap")
def tenant_bootstrap(slug: str = typer.Argument(..., help="Tenant slug")):
    """Re-run schema provisioning and role seeding for an existing tenant.

    Idempotent. Safe to run after schema migrations or to repair a tenant.
    """
    asyncio.run(_tenant_bootstrap(slug))


async def _tenant_bootstrap(slug: str) -> None:
    try:
        slug = validate_tenant_slug(slug)
    except ValidationError as exc:
        typer.echo(f"Invalid slug: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            tenant = (
                await session.execute(select(Tenant).where(Tenant.slug == slug))
            ).scalar_one_or_none()
            if tenant is None:
                typer.echo(
                    f"Tenant {slug!r} not found. Run `asterion tenant create` first.",
                    err=True,
                )
                raise typer.Exit(code=2)

        async with db.session() as session:
            await bootstrap_tenant(slug, session, database_url=config.database_url)

        typer.echo(f"Tenant {slug!r} bootstrapped.")
    finally:
        await db.dispose()


@tenant_app.command("upgrade")
def tenant_upgrade(
    all: bool = typer.Option(False, "--all", help="Upgrade all active tenants"),
    slug: str | None = typer.Option(None, "--slug", help="Single tenant slug"),
):
    """Re-bootstrap one tenant (--slug) or every active tenant (--all)."""
    if all:
        asyncio.run(_tenant_upgrade_all())
    elif slug:
        asyncio.run(_tenant_bootstrap(slug))
    else:
        typer.echo("Provide --all or --slug <slug>.", err=True)
        raise typer.Exit(code=2)


async def _tenant_upgrade_all() -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            result = await session.execute(
                select(Tenant).where(Tenant.is_active == True)  # noqa: E712
            )
            tenants = list(result.scalars().all())
    finally:
        await db.dispose()

    if not tenants:
        typer.echo("No active tenants found.")
        return

    for tenant in tenants:
        await _tenant_bootstrap(tenant.slug)


@tenant_app.command("disable")
def tenant_disable(slug: str = typer.Argument(..., help="Tenant slug")):
    """Mark a tenant inactive. Reversible via ``tenant enable``."""
    asyncio.run(_tenant_set_active(slug, active=False))


@tenant_app.command("enable")
def tenant_enable(slug: str = typer.Argument(..., help="Tenant slug")):
    """Mark a tenant active."""
    asyncio.run(_tenant_set_active(slug, active=True))


async def _tenant_set_active(slug: str, *, active: bool) -> None:
    try:
        slug = validate_tenant_slug(slug)
    except ValidationError as exc:
        typer.echo(f"Invalid slug: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            async with session.begin():
                tenant = (
                    await session.execute(select(Tenant).where(Tenant.slug == slug))
                ).scalar_one_or_none()
                if tenant is None:
                    typer.echo(f"Tenant {slug!r} not found.", err=True)
                    raise typer.Exit(code=2)
                if tenant.is_active is active:
                    typer.echo(f"Tenant {slug!r} already {'enabled' if active else 'disabled'}.")
                    return
                tenant.is_active = active
        typer.echo(f"Tenant {slug!r} {'enabled' if active else 'disabled'}.")
    finally:
        await db.dispose()


# ---------------------------------------------------------------------------
# permissions sub-commands
# ---------------------------------------------------------------------------

APP_SPEC_ENV = "ASTERION_APP"


def _load_runtime_from_app_spec(app_spec: str):
    """Import ``module:attribute`` and return the ``AdminRuntime`` behind it.

    ``attribute`` may be either the FastAPI ``app`` instance or a zero-arg
    factory callable that returns one. A FastAPI instance is itself callable
    (as an ASGI app), so we check for the runtime first and only fall through
    to ``attr()`` for genuine factories.
    """
    from fastapi import FastAPI

    if ":" not in app_spec:
        typer.echo(
            f"Invalid --app value: {app_spec!r}. Expected 'module:attribute'.",
            err=True,
        )
        raise typer.Exit(code=2)
    module_name, attr_name = app_spec.split(":", 1)
    try:
        module = importlib.import_module(module_name)
    except ImportError as exc:
        typer.echo(f"Cannot import module {module_name!r}: {exc}", err=True)
        raise typer.Exit(code=2) from exc
    attr = getattr(module, attr_name, None)
    if attr is None:
        typer.echo(
            f"Module {module_name!r} has no attribute {attr_name!r}.",
            err=True,
        )
        raise typer.Exit(code=2)

    if isinstance(attr, FastAPI):
        fastapi_app = attr
    elif callable(attr):
        fastapi_app = attr()
    else:
        fastapi_app = attr

    runtime = getattr(getattr(fastapi_app, "state", None), "asterion", None)
    if runtime is None:
        typer.echo(
            f"{app_spec!r} does not look like an asterion app (missing app.state.asterion).",
            err=True,
        )
        raise typer.Exit(code=2)
    return runtime


def _load_registry_from_app_spec(app_spec: str):
    """Convenience wrapper — returns just the AdminRegistry."""
    return _load_runtime_from_app_spec(app_spec).registry


@permissions_app.command("sync")
def permissions_sync(
    app_spec: str = typer.Option(
        "",
        "--app",
        envvar=APP_SPEC_ENV,
        help=(
            "Application spec in 'module:attribute' form (or set "
            f"{APP_SPEC_ENV}). The attribute should be the FastAPI app "
            "returned from create_admin()."
        ),
    ),
    prune: bool = typer.Option(
        True,
        "--prune/--no-prune",
        help="Remove catalog entries (source=registry) that are no longer in the registry.",
    ),
):
    """Sync PermissionCatalog with the keys derived from the registered admins."""
    if not app_spec:
        typer.echo(
            f"Provide --app <module:attr> or set {APP_SPEC_ENV}.",
            err=True,
        )
        raise typer.Exit(code=2)
    runtime = _load_runtime_from_app_spec(app_spec)
    asyncio.run(_permissions_sync(runtime.registry, runtime.permission_registry, prune=prune))


async def _permissions_sync(registry, permission_registry, *, prune: bool) -> None:
    from asterion.authz import generate_permission_keys, sync_permission_catalog

    keys = generate_permission_keys(registry, permission_registry)
    if not keys:
        typer.echo("Registry is empty — nothing to sync.")
        return

    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            async with session.begin():
                result = await sync_permission_catalog(session, keys, prune=prune)
    finally:
        await db.dispose()

    typer.echo(
        f"PermissionCatalog synced: +{result.added} added, "
        f"-{result.removed} removed, ={result.kept} kept "
        f"(total now {result.total})."
    )


@permissions_app.command("list")
def permissions_list(
    source: str | None = typer.Option(
        None,
        "--source",
        help="Filter by source column (e.g. 'registry').",
    ),
):
    """List the current PermissionCatalog entries."""
    asyncio.run(_permissions_list(source))


async def _permissions_list(source: str | None) -> None:
    from asterion.models.permission_catalog import PermissionCatalog

    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            stmt = select(PermissionCatalog).order_by(PermissionCatalog.key)
            if source is not None:
                stmt = stmt.where(PermissionCatalog.source == source)
            rows = (await session.execute(stmt)).scalars().all()
    finally:
        await db.dispose()

    if not rows:
        typer.echo("No permission entries.")
        return

    typer.echo(f"{'KEY':<50} {'CATEGORY':<24} SOURCE")
    for row in rows:
        typer.echo(f"{row.key:<50} {(row.category or '-'):<24} {row.source or '-'}")


@permissions_app.command("check")
def permissions_check(
    key: str = typer.Argument(..., help="Permission key to validate."),
):
    """Validate the syntax of one permission key."""
    try:
        validated = validate_permission_key(key)
    except ValidationError as exc:
        typer.echo(f"INVALID: {exc}", err=True)
        raise typer.Exit(code=1) from exc
    typer.echo(f"OK: {validated}")


# ---------------------------------------------------------------------------
# user sub-commands
# ---------------------------------------------------------------------------


@user_app.command("list")
def user_list(
    inactive: bool = typer.Option(False, "--inactive", help="Include inactive users only."),
    superadmin: bool = typer.Option(False, "--superadmin", help="Only superadmins."),
    search: str | None = typer.Option(
        None, "--search", help="Substring match against email or full_name."
    ),
):
    """List users (defaults to all)."""
    asyncio.run(_user_list(inactive=inactive, superadmin=superadmin, search=search))


async def _user_list(*, inactive: bool, superadmin: bool, search: str | None) -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            stmt = select(User).order_by(User.email)
            if inactive:
                stmt = stmt.where(User.is_active == False)  # noqa: E712
            if superadmin:
                stmt = stmt.where(User.is_superadmin == True)  # noqa: E712
            if search:
                needle = f"%{search.strip()}%"
                from sqlalchemy import or_

                stmt = stmt.where(or_(User.email.ilike(needle), User.full_name.ilike(needle)))
            rows = (await session.execute(stmt)).scalars().all()
    finally:
        await db.dispose()

    if not rows:
        typer.echo("No users match.")
        return

    typer.echo(f"{'EMAIL':<32} {'FULL NAME':<24} ACTIVE SUPER")
    for u in rows:
        typer.echo(f"{u.email:<32} {(u.full_name or '-'):<24} {u.is_active!s:<6} {u.is_superadmin}")


@user_app.command("create")
def user_create(
    email: str = typer.Option(..., "--email"),
    password: str = typer.Option(
        ..., "--password", prompt=True, hide_input=True, confirmation_prompt=True
    ),
    full_name: str | None = typer.Option(None, "--full-name"),
    superadmin: bool = typer.Option(False, "--superadmin", help="Grant superadmin privilege."),
):
    """Create a new user. Fails if a user with this email already exists."""
    asyncio.run(
        _user_create(email=email, password=password, full_name=full_name, superadmin=superadmin)
    )


async def _user_create(
    *, email: str, password: str, full_name: str | None, superadmin: bool
) -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            async with session.begin():
                existing = await _find_user_by_email(session, email)
                if existing is not None:
                    typer.echo(
                        f"User {email!r} already exists. Use 'user enable' or "
                        "'user disable' to toggle, or update via SQL.",
                        err=True,
                    )
                    raise typer.Exit(code=2)
                session.add(
                    User(
                        email=email,
                        hashed_password=hash_password(password),
                        full_name=full_name,
                        is_active=True,
                        is_superadmin=superadmin,
                    )
                )
        typer.echo(f"User {email} created{' (superadmin)' if superadmin else ''}.")
    finally:
        await db.dispose()


@user_app.command("disable")
def user_disable(email: str = typer.Option(..., "--email")):
    """Mark a user inactive AND revoke every existing access token.

    Implementation: sets ``is_active=False`` and bumps ``token_version``
    so any in-flight token starts failing the ``tkv`` check.
    """
    asyncio.run(_user_set_active(email=email, active=False))


@user_app.command("enable")
def user_enable(email: str = typer.Option(..., "--email")):
    """Re-enable a previously disabled user. Does NOT issue tokens."""
    asyncio.run(_user_set_active(email=email, active=True))


async def _user_set_active(*, email: str, active: bool) -> None:
    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            async with session.begin():
                user = await _find_user_by_email(session, email)
                if user is None:
                    typer.echo(f"User {email!r} not found.", err=True)
                    raise typer.Exit(code=2)
                if user.is_active is active:
                    typer.echo(f"User {email!r} already {'enabled' if active else 'disabled'}.")
                    return
                user.is_active = active
                if not active:
                    # Disabling revokes existing tokens too.
                    user.token_version = (user.token_version or 0) + 1
        typer.echo(f"User {email} {'enabled' if active else 'disabled'}.")
    finally:
        await db.dispose()


# ---------------------------------------------------------------------------
# audit sub-commands
# ---------------------------------------------------------------------------


@audit_app.command("prune")
def audit_prune(
    days: int = typer.Option(
        90, "--days", min=1, help="Delete audit rows older than this many days."
    ),
    yes: bool = typer.Option(False, "--yes", help="Skip the interactive confirmation."),
):
    """Delete audit_logs rows older than ``--days``.

    Audit data grows unbounded by design. Schedule this as a cron job
    (or run manually) to keep the table size in check.
    """
    if not yes:
        typer.echo(f"About to delete audit rows older than {days} days.")
        confirm = typer.confirm("Proceed?")
        if not confirm:
            typer.echo("Aborted.")
            raise typer.Exit(code=1)

    asyncio.run(_audit_prune(days))


async def _audit_prune(days: int) -> None:
    from datetime import datetime, timedelta

    from sqlalchemy import delete

    from asterion.models.audit_log import AuditLog

    cutoff = datetime.now(UTC) - timedelta(days=days)

    config = _load_config()
    db = _make_db(config)
    try:
        async with db.session() as session:
            async with session.begin():
                result = await session.execute(delete(AuditLog).where(AuditLog.created_at < cutoff))
        deleted = result.rowcount if result.rowcount is not None else 0
        typer.echo(f"Pruned {deleted} audit row(s) older than {days} days.")
    finally:
        await db.dispose()


# ---------------------------------------------------------------------------
# Service-account commands
# ---------------------------------------------------------------------------


@service_account_app.command("create")
def service_account_create(
    tenant: str = typer.Option(..., "--tenant", help="Tenant slug to bind the account to."),
    label: str = typer.Option(..., "--label", help="Human label; names the role service:<label>."),
    permission: list[str] = typer.Option(
        [],
        "--permission",
        help="Permission key to grant (repeatable), e.g. admin.time_entries.create.",
    ),
    email: str | None = typer.Option(None, "--email", help="Override the synthetic email."),
    expires_minutes: int | None = typer.Option(
        None,
        "--expires-minutes",
        help="Access-token lifetime (defaults to access_token_expire_minutes).",
    ),
):
    """Provision a token-only service account and print a freshly minted token once.

    Creates an active, passwordless user bound to ``--tenant`` with the given
    permission keys (see :func:`asterion.auth.service_accounts.create_service_account`)
    and mints one access token. The token is shown ONCE — store it securely.
    """
    asyncio.run(_service_account_create(tenant, label, list(permission), email, expires_minutes))


async def _service_account_create(
    slug: str,
    label: str,
    permissions: list[str],
    email: str | None,
    expires_minutes: int | None,
) -> None:
    from asterion.auth.service_accounts import create_service_account
    from asterion.auth.tokens import create_access_token
    from asterion.tenancy.schema_names import make_tenant_schema_name
    from asterion.tenancy.schema_strategy import set_search_path

    try:
        validated = validate_tenant_slug(slug)
    except ValidationError as exc:
        typer.echo(f"Invalid slug: {exc}", err=True)
        raise typer.Exit(code=2) from exc

    config = _load_config()
    db = _make_db(config)
    token: str | None = None
    out_email: str | None = None
    out_id: str | None = None
    try:
        async with db.session() as session:
            async with session.begin():
                tenant_row = (
                    await session.execute(select(Tenant).where(Tenant.slug == validated))
                ).scalar_one_or_none()
                if tenant_row is None:
                    typer.echo(f"Tenant '{validated}' not found.", err=True)
                    raise typer.Exit(code=1)

                # RBAC tables are tenant-local — scope the session like the
                # request CRUD path does (PostgreSQL only).
                if "postgresql" in config.database_url:
                    await set_search_path(session, make_tenant_schema_name(validated))

                try:
                    user = await create_service_account(
                        session,
                        tenant_id=tenant_row.id,
                        label=label,
                        permission_keys=permissions,
                        email=email,
                    )
                except ValueError as exc:
                    typer.echo(f"Cannot create service account: {exc}", err=True)
                    raise typer.Exit(code=1) from exc

                # Mint inside the transaction so user.id / token_version are
                # loaded before commit expires the instance.
                out_id = str(user.id)
                out_email = user.email
                token = create_access_token(
                    user.id,
                    secret_key=config.secret_key,
                    algorithm=config.jwt_algorithm,
                    expires_minutes=expires_minutes or config.access_token_expire_minutes,
                    token_version=user.token_version,
                )
    finally:
        await db.dispose()

    typer.echo(f"Service account created: {out_email}")
    typer.echo(f"User ID: {out_id}")
    typer.echo("Access token (shown once — store it securely):")
    typer.echo(token)


if __name__ == "__main__":
    app()
